export function expertMain(knowledgeBase){
  const data=JSON.stringify(knowledgeBase).replaceAll('<','\\u003c');
  return `<style>
.expert-hero{padding:clamp(54px,8vw,108px) 0 42px;background:#171611;color:#fff}.expert-hero .eyebrow{color:#d9b85f}.expert-hero h1{max-width:920px;font-size:clamp(42px,7vw,82px);line-height:.95;margin:14px 0 24px}.expert-hero p{max-width:720px;color:#dedbd2;font-size:clamp(18px,2.1vw,23px);line-height:1.55}
.expert-app{padding:44px 0 90px;background:#f6f4ef}.expert-layout{display:grid;grid-template-columns:minmax(280px,360px) 1fr;gap:32px;align-items:start}.expert-panel{background:#fff;border:1px solid #ddd8cd;padding:26px;position:sticky;top:92px}.expert-panel h2{font-size:25px;margin:0 0 22px}.expert-field{display:block;margin:0 0 18px}.expert-field span{display:block;font-weight:700;margin-bottom:8px}.expert-field select,.expert-field input[type=number]{width:100%;min-height:48px;border:1px solid #bdb7aa;background:#fff;padding:10px 12px;font:inherit;color:#171611}.expert-budget{display:grid;grid-template-columns:1fr 1fr;gap:10px}.expert-advanced{border-top:1px solid #ddd8cd;margin-top:22px;padding-top:18px}.expert-advanced summary{font-weight:800;cursor:pointer}.expert-range{display:grid;grid-template-columns:1fr 42px;gap:10px;align-items:center;margin-top:13px}.expert-range label{font-size:14px}.expert-range output{text-align:right;font-weight:800}.expert-submit{width:100%;margin-top:24px}.expert-results-head{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:20px}.expert-results-head h2{font-size:clamp(29px,4vw,48px);margin:0}.expert-results-head p{margin:0;color:#68635a}.expert-list{display:grid;gap:18px}.expert-card{background:#fff;border:1px solid #ddd8cd;display:grid;grid-template-columns:190px 1fr;min-height:320px}.expert-card-media{display:flex;align-items:center;justify-content:center;padding:22px;background:#faf9f6}.expert-card-media img{display:block;width:100%;height:270px;object-fit:contain}.expert-card-body{padding:25px 28px;display:flex;flex-direction:column}.expert-rank{font-size:12px;font-weight:900;letter-spacing:.15em;text-transform:uppercase;color:#8d6a20}.expert-card h3{font-size:clamp(25px,3vw,37px);line-height:1.05;margin:8px 0 6px}.expert-house{color:#736d63;margin-bottom:17px}.expert-score{display:flex;gap:12px;align-items:center;margin-bottom:17px}.expert-score b{font-size:20px}.expert-score span{font-size:13px;color:#736d63}.expert-reasons{margin:0 0 12px;line-height:1.55}.expert-caution{font-size:14px;color:#68635a;margin:0 0 20px}.expert-card-foot{border-top:1px solid #ddd8cd;margin-top:auto;padding-top:18px;display:flex;align-items:center;justify-content:space-between;gap:15px}.expert-price{font-size:25px;font-weight:900}.expert-empty{background:#fff;border:1px solid #ddd8cd;padding:35px}.expert-method{margin-top:34px;padding:22px;border-left:3px solid #a98231;background:#fff}.expert-method h3{margin:0 0 8px}.expert-method p{margin:0;color:#68635a;line-height:1.55}
@media(max-width:850px){.expert-layout{grid-template-columns:1fr}.expert-panel{position:static}.expert-card{grid-template-columns:130px 1fr}.expert-card-media{padding:12px}.expert-card-media img{height:220px}.expert-card-body{padding:20px}.expert-results-head{display:block}.expert-results-head p{margin-top:8px}}
@media(max-width:520px){.expert-app{padding-top:24px}.expert-panel{padding:20px}.expert-card{grid-template-columns:1fr}.expert-card-media img{height:250px}.expert-card-body{padding:20px}.expert-card-foot{align-items:flex-start;flex-direction:column}.expert-budget{grid-template-columns:1fr}}
</style>
<section class="expert-hero"><div class="container"><div class="eyebrow">MOTEUR EXPERT · VERSION 1</div><h1>Décrivez le champagne que vous recherchez.</h1><p>Le moteur confronte votre usage, vos goûts et votre budget à douze dimensions de style. Les contraintes commerciales restent des filtres : elles ne modifient jamais l’analyse.</p></div></section>
<section class="expert-app"><div class="container expert-layout">
  <form class="expert-panel" id="expert-form"><h2>Votre recherche</h2>
    <label class="expert-field"><span>Pour quel moment ?</span><select name="occasion"><option value="occ_apero">Apéritif</option><option value="occ_diner">Repas</option><option value="occ_cadeau">Cadeau</option><option value="occ_romantique">Dîner à deux</option><option value="occ_fete">Célébration</option></select></label>
    <label class="expert-field"><span>Avec quoi ?</span><select name="pairing"><option value="accord_any">Sans accord précis</option><option value="accord_mer">Huîtres, crustacés ou poisson</option><option value="accord_volaille">Volaille ou viande blanche</option><option value="accord_fromage">Fromage</option><option value="accord_dessert">Dessert</option><option value="accord_aperitif">Bouchées apéritives</option></select></label>
    <label class="expert-field"><span>Quel style ?</span><select name="preset"><option value="balanced">Équilibré et polyvalent</option><option value="fresh">Vif et minéral</option><option value="fruity">Rond et fruité</option><option value="gastronomic">Puissant et gastronomique</option><option value="complex">Complexe et brioché</option><option value="delicate">Fin et délicat</option></select></label>
    <div class="expert-field"><span>Budget par bouteille</span><div class="expert-budget"><input name="budgetMin" type="number" min="0" step="5" placeholder="Minimum"><input name="budgetMax" type="number" min="0" step="5" value="80" aria-label="Budget maximum"></div></div>
    <label class="expert-field"><span>Producteur</span><select name="producerType"><option value="any">Tous</option><option value="maison">Maison</option><option value="vigneron">Vigneron</option></select></label>
    <label class="expert-field"><span>Signature recherchée</span><select name="signature"><option value="any">Aucune contrainte</option><option value="low_dosage">Dosage bas</option><option value="rose">Rosé</option><option value="blanc_de_blancs">Blanc de blancs</option><option value="vintage">Millésimé</option><option value="grand_cru">Grand cru</option></select></label>
    <label class="expert-field"><span>Votre expérience</span><select name="experience"><option value="discovery">Je découvre</option><option value="regular" selected>J’en bois régulièrement</option><option value="expert">Je recherche une cuvée exigeante</option></select></label>
    <details class="expert-advanced"><summary>Affiner le profil</summary><div class="expert-range"><label for="freshness">Fraîcheur</label><output>3</output><input id="freshness" name="freshness" type="range" min="1" max="5" step=".5" value="3"></div><div class="expert-range"><label for="roundness">Rondeur</label><output>3</output><input id="roundness" name="roundness" type="range" min="1" max="5" step=".5" value="3"></div><div class="expert-range"><label for="power">Puissance</label><output>3</output><input id="power" name="power" type="range" min="1" max="5" step=".5" value="3"></div><div class="expert-range"><label for="complexity">Complexité</label><output>3</output><input id="complexity" name="complexity" type="range" min="1" max="5" step=".5" value="3"></div></details>
    <button class="btn btn-primary expert-submit" type="submit">Analyser les cuvées</button>
  </form>
  <div><div class="expert-results-head"><h2>Les choix les plus cohérents</h2><p id="expert-count"></p></div><div class="expert-list" id="expert-results" aria-live="polite"></div><div class="expert-method"><h3>Une recommandation explicable</h3><p>Chaque résultat indique les critères qui ont pesé dans le choix. La base distingue l’identité de la cuvée, ses caractéristiques techniques, son profil éditorial et l’offre marchande du jour.</p></div></div>
</div></section>
<script type="application/json" id="expert-data">${data}</script>
<script type="module">
import {recommend} from '/assets/expert-engine.js';
const kb=JSON.parse(document.getElementById('expert-data').textContent);const form=document.getElementById('expert-form');const results=document.getElementById('expert-results');const count=document.getElementById('expert-count');
document.querySelectorAll('.expert-range input').forEach(input=>{const output=input.parentElement.querySelector('output');const sync=()=>output.value=input.value;input.addEventListener('input',sync);sync()});
function esc(value){return String(value||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function run(){const d=new FormData(form);const number=name=>d.get(name)===''?undefined:Number(d.get(name));const request={occasion:d.get('occasion'),pairing:d.get('pairing'),preset:d.get('preset'),budgetMin:number('budgetMin'),budgetMax:number('budgetMax'),producerType:d.get('producerType'),signature:d.get('signature'),experience:d.get('experience'),availableOnly:true,axes:{freshness:number('freshness'),roundness:number('roundness'),power:number('power'),complexity:number('complexity')}};const picks=recommend(kb,request,{limit:3});count.textContent=kb.records.filter(r=>r.commerce.available).length+' cuvées disponibles analysées';if(!picks.length){results.innerHTML='<div class="expert-empty"><h3>Aucune cuvée ne respecte toutes ces contraintes.</h3><p>Élargissez le budget ou retirez une signature pour relancer l’analyse.</p></div>';return}const productBase=String.fromCharCode(47,99,104,97,109,112,97,103,110,101,47);results.innerHTML=picks.map((pick,index)=>{const r=pick.record;const price=Number(r.commerce.price).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';const fitLabel=pick.assessment.score>=85?'Très forte cohérence':pick.assessment.score>=72?'Forte cohérence':'Alternative pertinente';return '<article class="expert-card"><div class="expert-card-media"><img src="'+esc(r.commerce.image)+'" alt="'+esc(r.identity.house+' '+r.identity.cuvee)+'"></div><div class="expert-card-body"><div class="expert-rank">Choix '+(index+1)+'</div><h3>'+esc(r.identity.cuvee)+'</h3><div class="expert-house">'+esc(r.identity.house)+'</div><div class="expert-score"><b>'+fitLabel+'</b><span>avec votre recherche</span></div><p class="expert-reasons">'+esc(pick.explanation.headline)+'</p><p class="expert-caution">'+esc(pick.explanation.caution||'Profil sans écart notable sur les critères choisis.')+'</p><div class="expert-card-foot"><span class="expert-price">'+price+'</span><a class="chev" href="'+productBase+encodeURIComponent(r.id)+'/">Lire l’analyse</a></div></div></article>'}).join('')}
form.addEventListener('submit',event=>{event.preventDefault();run();results.scrollIntoView({behavior:'smooth',block:'start'})});form.addEventListener('change',run);run();
</script>`;
}
